import { Recipe } from '@/types';

export const RECIPES: Recipe[] = [
  {
    id: 'r1',
    title: 'Frittata di spinaci',
    time: '20 min',
    difficulty: 'Facile',
    tint: '#e6efde',
    uses: ['Spinaci freschi', 'Uova fresche x6', 'Parmigiano 24 mesi'],
    tag: 'Salva 3 ingredienti',
    desc: 'Una frittata morbida che sfrutta gli spinaci e le uova in dispensa.',
    steps: [
      'Sbatti 4 uova con un pizzico di sale e parmigiano grattugiato.',
      'Salta gli spinaci in padella con un filo d\'olio.',
      'Versa le uova, copri e cuoci a fuoco basso 6 minuti per lato.',
    ],
  },
  {
    id: 'r2',
    title: 'Pasta al pomodoro fresco',
    time: '25 min',
    difficulty: 'Facile',
    tint: '#f4dad0',
    uses: ['Pomodori ciliegia', 'Pasta Penne', 'Olio EVO'],
    tag: 'Pronta in 25 minuti',
    desc: 'I pomodorini stanno per scadere — qui brillano con basilico e olio EVO.',
    steps: [
      'Taglia i pomodorini a metà, fai rosolare in olio caldo con aglio.',
      'Cuoci la pasta al dente e salta in padella.',
      'Manteca con parmigiano e basilico fresco.',
    ],
  },
  {
    id: 'r3',
    title: 'Yogurt bowl con miele',
    time: '5 min',
    difficulty: 'Velocissima',
    tint: '#f1ede0',
    uses: ['Yogurt greco'],
    tag: 'Pronta in 5 min',
    desc: 'Il modo più veloce per finire lo yogurt prima di domani.',
    steps: [
      'Versa lo yogurt in una ciotola.',
      'Aggiungi miele, granola e frutta secca.',
      'Gusta subito.',
    ],
  },
  {
    id: 'r4',
    title: 'Pollo al limone',
    time: '30 min',
    difficulty: 'Media',
    tint: '#f3e9e0',
    uses: ['Pollo a fette', 'Olio EVO'],
    tag: 'Cena leggera',
    desc: 'Petto di pollo marinato e cotto in padella.',
    steps: [
      'Marina il pollo con succo di limone, olio, sale e timo (10 min).',
      'Cuoci in padella ben calda 4 minuti per lato.',
      'Sfuma con altro limone e servi caldo.',
    ],
  },
  {
    id: 'r5',
    title: 'Risotto al parmigiano',
    time: '35 min',
    difficulty: 'Media',
    tint: '#f6f0dc',
    uses: ['Riso Arborio', 'Parmigiano 24 mesi'],
    tag: 'Comfort food',
    desc: 'Cremoso, ricco, perfetto per le sere d\'autunno.',
    steps: [
      'Tosta il riso, sfuma con vino bianco.',
      'Aggiungi brodo poco a poco mescolando.',
      'A fine cottura manteca con burro e parmigiano.',
    ],
  },
];
